---
title: "Predicting Personality from Mobile Data Use"
author: "Sebastian Marin"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
    code_folding: hide
---

```{r setup, include = F}
library(knitr)
library(rmdformats)
library(tidyverse)
library(caret)
library(doParallel)
library(DT)
library(data.table)

# global options
opts_chunk$set(echo=T, cache=T,prompt=F,tidy=T,comment=NA,message=F,warning=F)
```

# R Studio API Code
```{r}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

# Data Importing and Cleaning
```{r}
df = read_csv("macaco_dataset.csv")[,-1]
```

# Analysis
```{r}
cores = detectCores() - 1
cl = makeCluster(cores)
registerDoParallel(cl)

model_O = train(O ~ .,
                data = df,
                method = "glmnet",
                preProcess = c("center","scale","zv"),
                trControl = trainControl(
                  method = "cv",
                  number = 10,
                  verboseIter = T
                )
)
model_C = train(C ~ .,
                data = df,
                method = "glmnet",
                preProcess = c("center","scale","zv"),
                trControl = trainControl(
                  method = "cv",
                  number = 10,
                  verboseIter = T
                )
)
model_E = train(E ~ .,
                data = df,
                method = "glmnet",
                preProcess = c("center","scale","zv"),
                trControl = trainControl(
                  method = "cv",
                  number = 10,
                  verboseIter = T
                )
)
model_A = train(A ~ .,
                data = df,
                method = "glmnet",
                preProcess = c("center","scale","zv"),
                trControl = trainControl(
                  method = "cv",
                  number = 10,
                  verboseIter = T
                )
)
model_N = train(A ~ .,
                data = df,
                method = "glmnet",
                preProcess = c("center","scale","zv"),
                trControl = trainControl(
                  method = "cv",
                  number = 10,
                  verboseIter = T
                )
)

stopCluster(cl)
registerDoSEQ()

```

# Visualization

```{r}
imp_tbl = tibble(
  variables = names(df),
  openness= append(varImp(model_O)$importance$Overall,NA),
  extraversion = append(varImp(model_E)$importance$Overall,NA,after=346),
  agreeableness = append(varImp(model_A)$importance$Overall,NA,after=347),
  conscientiousness = append(varImp(model_C)$importance$Overall,NA,after=348),
  neurotocism = append(varImp(model_N)$importance$Overall,NA,after=349)
)
datatable(imp_tbl)
```
